-- ============================================================================
-- AI Operations — Central Agent Registry — live seed (Phase 2 Prompt 03).
--
-- Idempotent import of the 76 demo agents (16 core/shared + 60 site-specific)
-- into `ai_operations_agents`. `agent_key` is the stable application
-- identifier (unique) and is used for upsert, so re-running this migration
-- never duplicates rows. `site_id` is resolved from the live `ai_sites`
-- registry via `site_key` subqueries; group/shared agents keep `site_id = NULL`.
--
-- Safety:
--   * No secrets / credentials are imported — only safe metadata + reference
--     strings (model references are "Provider / Model" labels, never keys).
--   * `current_run_id` is intentionally left NULL (demo run ids are not real
--     UUIDs and are not linked live yet).
--   * `is_active = true` for all real registry entries (paused/disabled agents
--     remain visible; their `status` field captures the state). The Prompt-01
--     TEST/SANDBOX seed keeps `is_active = false` and is unaffected here.
-- ============================================================================

INSERT INTO ai_operations_agents (agent_key, name, description, agent_type, category, site_id, environment, status, health, risk_level, autonomy_level, owner_team, escalation_team, primary_model_reference, fallback_model_reference, prompt_version_reference, current_task, queue_count, success_rate, notes, is_active) VALUES
('core-orchestrator','DFP Group Master Orchestrator','Routes AI tasks to the correct group, site and specialist agent while enforcing permissions, approvals and audit controls.','core','orchestration',NULL,'production','working','healthy','high','autonomous','DFP Core Team','Group Incident Team','Anthropic / Claude Sonnet','OpenAI / GPT-4o','prompt-registry/v2','Dispatching tasks across the group',5,99.4,'Highest-privilege routing agent. All red-class actions remain human-approved.',true),
('core-site-registry','Site Registry Agent','Maintains the group-wide inventory of sites, platforms and their connections.','core','data',NULL,'production','active','healthy','low','limited_automatic','DFP Core Team','Group Incident Team','Anthropic / Claude Sonnet','OpenAI / GPT-4o','prompt-registry/v2','Syncing site metadata',0,99.8,'Single source of truth for the Group Site Registry.',true),
('core-support','Support Agent','Triages and assists with support enquiries across the group.','core','support',NULL,'production','active','healthy','low','limited_automatic','DFP Support','Group Incident Team','Anthropic / Claude Sonnet','OpenAI / GPT-4o','prompt-registry/v2','Standing by for enquiries',2,97.9,'Shared support assistant; site-specific support agents specialise further.',true),
('core-diagnostics','Diagnostics Agent','Investigates incidents and probes system health across group platforms.','core','diagnostics',NULL,'production','working','healthy','medium','limited_automatic','DFP Core Team','Group Incident Team','Anthropic / Claude Sonnet','OpenAI / GPT-4o','prompt-registry/v2','Investigating support incident',1,97.3,'Non-destructive diagnosis only; repairs route through approvals.',true),
('core-security','Security Agent','Monitors for security events and flags anomalies for human review.','core','security',NULL,'production','active','healthy','high','human_approval_required','DFP Security','Group Incident Team','Anthropic / Claude Sonnet','OpenAI / GPT-4o','prompt-registry/v2','Scanning for anomalies',0,99.1,'All actions require human approval. Never modifies access controls automatically.',true),
('core-data-health','Data Health Agent','Checks data quality, consistency and integrity across group databases.','core','data',NULL,'production','active','healthy','medium','recommend_only','DFP Core Team','Group Incident Team','Anthropic / Claude Sonnet','OpenAI / GPT-4o','prompt-registry/v2','Running integrity checks',0,98.6,'Recommend-only — surfaces findings for human remediation.',true),
('core-repair','Repair Recommendation Agent','Proposes repair actions based on diagnostics findings for human approval.','core','repair',NULL,'production','idle','healthy','medium','recommend_only','DFP Core Team','Group Incident Team','Anthropic / Claude Sonnet','OpenAI / GPT-4o','prompt-registry/v2','Awaiting diagnostics input',0,96.9,'Produces recommendations only; execution requires human approval.',true),
('core-uat','UAT Agent','Runs user-acceptance tests and release validation across group platforms.','core','uat',NULL,'production','active','healthy','low','limited_automatic','DFP Core Team','Group Incident Team','Anthropic / Claude Sonnet','OpenAI / GPT-4o','prompt-registry/v2','Awaiting release build',0,96.8,'Sandboxed test execution only.',true),
('core-monitoring','Monitoring Agent','Continuously observes platform health and raises alerts on anomalies.','core','monitoring',NULL,'production','active','healthy','low','observe_only','DFP Core Team','Group Incident Team','Anthropic / Claude Sonnet','OpenAI / GPT-4o','prompt-registry/v2','Watching live metrics',0,99.9,'Observe-only — never takes corrective action.',true),
('core-comms','Communications Agent','Drafts and sends approved communications to customers and staff.','core','communications',NULL,'production','active','healthy','low','limited_automatic','DFP Core Team','Group Incident Team','Anthropic / Claude Sonnet','OpenAI / GPT-4o','prompt-registry/v2','Queuing notifications',3,98.9,'Sends pre-approved templates only.',true),
('core-billing','Billing Agent','Reconciles billing records and flags payment anomalies for finance review.','core','billing',NULL,'production','paused','warning','high','human_approval_required','DFP Finance','Group Incident Team','Anthropic / Claude Sonnet','OpenAI / GPT-4o','prompt-registry/v2','Paused — awaiting policy review',0,97.7,'Finance-critical — all changes require human approval.',true),
('core-lead','Lead / CRM Agent','Processes inbound leads, enriches CRM records and scores opportunities.','core','crm',NULL,'production','active','healthy','medium','limited_automatic','DFP Growth','Group Incident Team','Anthropic / Claude Sonnet','OpenAI / GPT-4o','prompt-registry/v2','Processing new business enquiry',4,98.2,'Lead scoring and enrichment; no automated outreach without approval.',true),
('core-knowledge','Knowledge Agent','Curates and retrieves knowledge-base articles for staff and support agents.','core','data',NULL,'production','active','healthy','low','recommend_only','DFP Core Team','Group Incident Team','Anthropic / Claude Sonnet','OpenAI / GPT-4o','prompt-registry/v2','Indexing new articles',0,99.3,'Read + recommend for knowledge content.',true),
('core-deploy','Deployment Agent','Coordinates production deployments and release gates (currently disabled).','core','infrastructure',NULL,'production','disabled','unknown','critical','human_approval_required','DFP Core Team','Group Incident Team','Anthropic / Claude Sonnet','OpenAI / GPT-4o','prompt-registry/v2','Disabled — pending release policy',0,NULL,'Deployment is gated behind a full release approval workflow.',true),
('core-reporting','Reporting Agent','Generates operational and business reports from group data.','core','reporting',NULL,'production','active','healthy','low','observe_only','DFP Core Team','Group Incident Team','Anthropic / Claude Sonnet','OpenAI / GPT-4o','prompt-registry/v2','Compiling daily report',1,99.0,'Read-only reporting across permitted datasets.',true),
('core-backup','Backup / Recovery Agent','Orchestrates backups and verifies recovery readiness across group data.','core','infrastructure',NULL,'production','active','healthy','medium','limited_automatic','DFP Core Team','Group Incident Team','Anthropic / Claude Sonnet','OpenAI / GPT-4o','prompt-registry/v2','Verifying latest backup',0,99.7,'Backup and restore verification; destructive restores require approval.',true)
ON CONFLICT (agent_key) DO UPDATE SET name=EXCLUDED.name, description=EXCLUDED.description, agent_type=EXCLUDED.agent_type, category=EXCLUDED.category, site_id=EXCLUDED.site_id, environment=EXCLUDED.environment, status=EXCLUDED.status, health=EXCLUDED.health, risk_level=EXCLUDED.risk_level, autonomy_level=EXCLUDED.autonomy_level, owner_team=EXCLUDED.owner_team, escalation_team=EXCLUDED.escalation_team, primary_model_reference=EXCLUDED.primary_model_reference, fallback_model_reference=EXCLUDED.fallback_model_reference, prompt_version_reference=EXCLUDED.prompt_version_reference, current_task=EXCLUDED.current_task, queue_count=EXCLUDED.queue_count, success_rate=EXCLUDED.success_rate, notes=EXCLUDED.notes, is_active=EXCLUDED.is_active;

INSERT INTO ai_operations_agents (agent_key, name, description, agent_type, category, site_id, environment, status, health, risk_level, autonomy_level, owner_team, escalation_team, primary_model_reference, fallback_model_reference, prompt_version_reference, current_task, queue_count, success_rate, notes, is_active) VALUES
('dfp-lead','Lead Qualification Agent','Scores and qualifies inbound business enquiries for Digital Footprint.','site_specific','crm',(SELECT id FROM ai_sites WHERE site_key='digital-footprint'),'production','active','healthy','low','limited_automatic','DFP Growth','DFP Support','Anthropic / Claude Sonnet','OpenAI / GPT-4o','prompt-registry/v2','Scoring inbound enquiries',3,98.6,'Lead scoring only; no automated outreach.',true),
('dfp-onboard','Client Onboarding Agent','Prepares onboarding checklists and setup tasks for new clients.','site_specific','operations',(SELECT id FROM ai_sites WHERE site_key='digital-footprint'),'production','active','healthy','low','limited_automatic','DFP Delivery','DFP Support','Anthropic / Claude Sonnet','OpenAI / GPT-4o','prompt-registry/v2','Preparing onboarding checklist',1,99.1,'Guides clients through onboarding workflows.',true),
('dfp-diag','Digital Footprint Diagnostics Agent','Runs diagnostics on the Digital Footprint platform and its services.','site_specific','diagnostics',(SELECT id FROM ai_sites WHERE site_key='digital-footprint'),'production','active','healthy','medium','limited_automatic','DFP Core Team','Group Incident Team','Anthropic / Claude Sonnet','OpenAI / GPT-4o','prompt-registry/v2','Probing support incident',0,97.3,'Platform-specific diagnostics for Digital Footprint.',true),
('dfp-portal','Client Portal Agent','Assists clients using the Digital Footprint client portal.','site_specific','support',(SELECT id FROM ai_sites WHERE site_key='digital-footprint'),'production','idle','healthy','low','limited_automatic','DFP Support','DFP Support','Anthropic / Claude Sonnet','OpenAI / GPT-4o','prompt-registry/v2','Standing by',0,98.4,'Client portal guidance and support.',true),
('dfp-uat','UAT Coordinator Agent','Coordinates UAT cycles for Digital Footprint releases.','site_specific','uat',(SELECT id FROM ai_sites WHERE site_key='digital-footprint'),'production','idle','healthy','low','limited_automatic','DFP Core Team','Group Incident Team','Anthropic / Claude Sonnet','OpenAI / GPT-4o','prompt-registry/v2','Awaiting release build',0,96.8,'UAT coordination for Digital Footprint.',true),
('qg-match','Guard Matching Agent','Matches eligible guards to shifts based on availability, qualifications and location.','site_specific','matching',(SELECT id FROM ai_sites WHERE site_key='quickguard'),'production','working','healthy','medium','limited_automatic','QuickGuard Ops','QuickGuard Escalations','Anthropic / Claude Sonnet','OpenAI / GPT-4o','prompt-registry/v2','Matching eligible guards to shift',2,99.0,'Produces match recommendations; final assignment confirmed by staff.',true),
('qg-shift','Shift Management Agent','Rebalances rota coverage and manages shift allocation for QuickGuard.','site_specific','operations',(SELECT id FROM ai_sites WHERE site_key='quickguard'),'production','active','healthy','medium','limited_automatic','QuickGuard Ops','QuickGuard Escalations','Anthropic / Claude Sonnet','OpenAI / GPT-4o','prompt-registry/v2','Rebalancing rota coverage',0,98.4,'Rota and shift optimisation.',true),
('qg-comp','Guard Compliance Agent','Verifies guard licences, training and compliance requirements.','site_specific','compliance',(SELECT id FROM ai_sites WHERE site_key='quickguard'),'production','active','healthy','high','recommend_only','QuickGuard Ops','QuickGuard Escalations','Anthropic / Claude Sonnet','OpenAI / GPT-4o','prompt-registry/v2','Verifying licence renewals',0,97.8,'Compliance checks surface findings for human review.',true),
('qg-employer-support','Employer Support Agent','Assists employers with QuickGuard service enquiries and account support.','site_specific','support',(SELECT id FROM ai_sites WHERE site_key='quickguard'),'production','active','healthy','low','limited_automatic','QuickGuard Support','QuickGuard Escalations','Anthropic / Claude Sonnet','OpenAI / GPT-4o','prompt-registry/v2','Responding to employer enquiry',1,97.6,'Employer-facing support.',true),
('qg-support','Guard Support Agent','Assists guards with shift, pay and account support enquiries.','site_specific','support',(SELECT id FROM ai_sites WHERE site_key='quickguard'),'production','idle','healthy','low','limited_automatic','QuickGuard Support','QuickGuard Escalations','Anthropic / Claude Sonnet','OpenAI / GPT-4o','prompt-registry/v2','Standing by for enquiries',0,96.9,'Guard-facing support.',true),
('qg-timesheet','Timesheet Agent','Processes and validates guard timesheets and hours.','site_specific','operations',(SELECT id FROM ai_sites WHERE site_key='quickguard'),'production','active','healthy','medium','limited_automatic','QuickGuard Ops','QuickGuard Escalations','Anthropic / Claude Sonnet','OpenAI / GPT-4o','prompt-registry/v2','Validating submitted hours',0,98.7,'Timesheet validation and reconciliation.',true),
('qg-incident','Incident Agent','Captures and triages security and operational incidents for QuickGuard.','site_specific','security',(SELECT id FROM ai_sites WHERE site_key='quickguard'),'production','idle','healthy','high','human_approval_required','QuickGuard Ops','QuickGuard Escalations','Anthropic / Claude Sonnet','OpenAI / GPT-4o','prompt-registry/v2','Monitoring incident queue',0,99.3,'Incident triage; escalates to humans.',true),
('qg-launch','Launch Rewards Agent','Manages launch reward eligibility and payouts for QuickGuard.','site_specific','billing',(SELECT id FROM ai_sites WHERE site_key='quickguard'),'production','active','healthy','medium','human_approval_required','QuickGuard Ops','QuickGuard Escalations','Anthropic / Claude Sonnet','OpenAI / GPT-4o','prompt-registry/v2','Calculating reward eligibility',0,98.1,'Reward calculations; payouts require approval.',true),
('qg-payment','Payment Agent','Processes guard payroll and payment reconciliation for QuickGuard.','site_specific','billing',(SELECT id FROM ai_sites WHERE site_key='quickguard'),'production','active','healthy','high','human_approval_required','QuickGuard Finance','QuickGuard Escalations','Anthropic / Claude Sonnet','OpenAI / GPT-4o','prompt-registry/v2','Reconciling payroll batch',0,99.2,'Payroll is finance-critical; human approval required.',true),
('gh-onboarding','Security Company Onboarding Agent','Onboards security companies and their care operations onto GuardianHub.','site_specific','operations',(SELECT id FROM ai_sites WHERE site_key='guardianhub'),'production','active','healthy','medium','limited_automatic','GuardianHub Ops','GuardianHub Escalations','Anthropic / Claude Sonnet','OpenAI / GPT-4o','prompt-registry/v2','Processing company onboarding',1,98.0,'Guides security companies through onboarding.',true),
('gh-guard','Guard Management Agent','Manages guard records, rota participation and assignments.','site_specific','operations',(SELECT id FROM ai_sites WHERE site_key='guardianhub'),'production','active','healthy','medium','limited_automatic','GuardianHub Ops','GuardianHub Escalations','Anthropic / Claude Sonnet','OpenAI / GPT-4o','prompt-registry/v2','Updating guard records',0,98.3,'Guard record management.',true),
('gh-rota','Rota Agent','Optimises weekly rotas and shift coverage for care operations.','site_specific','operations',(SELECT id FROM ai_sites WHERE site_key='guardianhub'),'production','active','healthy','medium','limited_automatic','GuardianHub Ops','GuardianHub Escalations','Anthropic / Claude Sonnet','OpenAI / GPT-4o','prompt-registry/v2','Optimising weekly rota',0,97.5,'Rota optimisation for care teams.',true),
('gh-site-assignment','Site Assignment Agent','Assigns guards to client sites based on requirements and availability.','site_specific','matching',(SELECT id FROM ai_sites WHERE site_key='guardianhub'),'production','active','healthy','medium','limited_automatic','GuardianHub Ops','GuardianHub Escalations','Anthropic / Claude Sonnet','OpenAI / GPT-4o','prompt-registry/v2','Assigning guard to site',1,98.0,'Site assignment recommendations.',true),
('gh-checkcall','Check-Call Agent','Coordinates welfare check-calls and records outcomes.','site_specific','monitoring',(SELECT id FROM ai_sites WHERE site_key='guardianhub'),'production','error','warning','high','limited_automatic','GuardianHub Ops','GuardianHub Escalations','Anthropic / Claude Sonnet','OpenAI / GPT-4o','prompt-registry/v2','Retrying failed check-call',1,94.2,'Welfare check-calls — elevated latency under investigation.',true),
('gh-incident','Incident Agent','Captures and escalates care and welfare incidents.','site_specific','security',(SELECT id FROM ai_sites WHERE site_key='guardianhub'),'production','idle','healthy','critical','human_approval_required','GuardianHub Ops','GuardianHub Escalations','Anthropic / Claude Sonnet','OpenAI / GPT-4o','prompt-registry/v2','Monitoring incident queue',0,99.3,'Incident handling — human escalation required.',true),
('gh-welfare','Welfare Agent','Monitors welfare signals and escalates concerning patterns.','site_specific','monitoring',(SELECT id FROM ai_sites WHERE site_key='guardianhub'),'production','active','healthy','high','human_approval_required','GuardianHub Ops','GuardianHub Escalations','Anthropic / Claude Sonnet','OpenAI / GPT-4o','prompt-registry/v2','Escalating welfare flag',0,98.8,'Welfare monitoring — sensitive, human-reviewed.',true),
('gh-comp','Compliance Agent','Verifies care compliance, certifications and regulatory requirements.','site_specific','compliance',(SELECT id FROM ai_sites WHERE site_key='guardianhub'),'production','active','healthy','high','recommend_only','GuardianHub Ops','GuardianHub Escalations','Anthropic / Claude Sonnet','OpenAI / GPT-4o','prompt-registry/v2','Reviewing compliance checks',0,98.9,'Compliance findings surfaced for human review.',true),
('gh-timesheet','Timesheet Agent','Processes and validates care team timesheets.','site_specific','operations',(SELECT id FROM ai_sites WHERE site_key='guardianhub'),'production','active','healthy','medium','limited_automatic','GuardianHub Ops','GuardianHub Escalations','Anthropic / Claude Sonnet','OpenAI / GPT-4o','prompt-registry/v2','Validating timesheet batch',0,98.5,'Timesheet processing.',true),
('gh-supervisor','Supervisor Assistant Agent','Assists supervisors with rota, escalation and daily operations.','site_specific','support',(SELECT id FROM ai_sites WHERE site_key='guardianhub'),'production','active','healthy','medium','limited_automatic','GuardianHub Ops','GuardianHub Escalations','Anthropic / Claude Sonnet','OpenAI / GPT-4o','prompt-registry/v2','Drafting supervisor summary',0,97.9,'Supervisor assistance and summaries.',true)
ON CONFLICT (agent_key) DO UPDATE SET name=EXCLUDED.name, description=EXCLUDED.description, agent_type=EXCLUDED.agent_type, category=EXCLUDED.category, site_id=EXCLUDED.site_id, environment=EXCLUDED.environment, status=EXCLUDED.status, health=EXCLUDED.health, risk_level=EXCLUDED.risk_level, autonomy_level=EXCLUDED.autonomy_level, owner_team=EXCLUDED.owner_team, escalation_team=EXCLUDED.escalation_team, primary_model_reference=EXCLUDED.primary_model_reference, fallback_model_reference=EXCLUDED.fallback_model_reference, prompt_version_reference=EXCLUDED.prompt_version_reference, current_task=EXCLUDED.current_task, queue_count=EXCLUDED.queue_count, success_rate=EXCLUDED.success_rate, notes=EXCLUDED.notes, is_active=EXCLUDED.is_active;

INSERT INTO ai_operations_agents (agent_key, name, description, agent_type, category, site_id, environment, status, health, risk_level, autonomy_level, owner_team, escalation_team, primary_model_reference, fallback_model_reference, prompt_version_reference, current_task, queue_count, success_rate, notes, is_active) VALUES
('lh-landlord','Landlord Agent','Assists landlords with property listings and letting management.','site_specific','support',(SELECT id FROM ai_sites WHERE site_key='lethub'),'production','active','healthy','low','limited_automatic','LetHub Ops','LetHub Escalations','Anthropic / Claude Sonnet','OpenAI / GPT-4o','prompt-registry/v2','Assisting landlord enquiry',1,98.2,'Landlord-facing support.',true),
('lh-tenant','Tenant Agent','Assists tenants with tenancy enquiries and support requests.','site_specific','support',(SELECT id FROM ai_sites WHERE site_key='lethub'),'production','active','healthy','low','limited_automatic','LetHub Support','LetHub Escalations','Anthropic / Claude Sonnet','OpenAI / GPT-4o','prompt-registry/v2','Responding to tenant enquiry',2,98.0,'Tenant-facing support.',true),
('lh-property','Property Agent','Manages property records, listings and lettings data.','site_specific','data',(SELECT id FROM ai_sites WHERE site_key='lethub'),'production','active','healthy','medium','limited_automatic','LetHub Ops','LetHub Escalations','Anthropic / Claude Sonnet','OpenAI / GPT-4o','prompt-registry/v2','Updating property listing',0,98.6,'Property data management.',true),
('lh-tenancy','Tenancy Agent','Processes tenancy renewals, changes and agreements.','site_specific','operations',(SELECT id FROM ai_sites WHERE site_key='lethub'),'production','active','healthy','medium','limited_automatic','LetHub Ops','LetHub Escalations','Anthropic / Claude Sonnet','OpenAI / GPT-4o','prompt-registry/v2','Processing tenancy renewal',0,98.1,'Tenancy lifecycle management.',true),
('lh-maint','Maintenance Agent','Triages and coordinates maintenance and repair requests.','site_specific','repair',(SELECT id FROM ai_sites WHERE site_key='lethub'),'production','active','healthy','medium','limited_automatic','LetHub Ops','LetHub Escalations','Anthropic / Claude Sonnet','OpenAI / GPT-4o','prompt-registry/v2','Triaging maintenance request',1,97.7,'Maintenance coordination.',true),
('lh-comp','Compliance Agent','Reviews tenancy compliance, referencing and safety checks.','site_specific','compliance',(SELECT id FROM ai_sites WHERE site_key='lethub'),'production','active','healthy','high','recommend_only','LetHub Ops','LetHub Escalations','Anthropic / Claude Sonnet','OpenAI / GPT-4o','prompt-registry/v2','Reviewing tenancy compliance',0,98.9,'Compliance findings surfaced for review.',true),
('lh-rent','Rent Agent','Tracks rent payments, arrears and reconciliation.','site_specific','billing',(SELECT id FROM ai_sites WHERE site_key='lethub'),'production','idle','healthy','low','limited_automatic','LetHub Finance','LetHub Escalations','Anthropic / Claude Sonnet','OpenAI / GPT-4o','prompt-registry/v2','Reconciling rent ledger',0,99.2,'Rent tracking and reconciliation.',true),
('lh-document','Document Agent','Generates and manages tenancy documents and agreements.','site_specific','operations',(SELECT id FROM ai_sites WHERE site_key='lethub'),'production','active','healthy','medium','limited_automatic','LetHub Ops','LetHub Escalations','Anthropic / Claude Sonnet','OpenAI / GPT-4o','prompt-registry/v2','Generating tenancy agreement',0,98.8,'Document generation and management.',true),
('lh-inspection','Inspection Agent','Schedules and tracks property inspections and reports.','site_specific','operations',(SELECT id FROM ai_sites WHERE site_key='lethub'),'production','idle','healthy','medium','limited_automatic','LetHub Ops','LetHub Escalations','Anthropic / Claude Sonnet','OpenAI / GPT-4o','prompt-registry/v2','Queuing inspection reports',0,98.0,'Inspection scheduling and tracking.',true),
('lh-comms','Communications Agent','Drafts and sends approved communications to landlords and tenants.','site_specific','communications',(SELECT id FROM ai_sites WHERE site_key='lethub'),'production','active','healthy','low','limited_automatic','LetHub Ops','LetHub Escalations','Anthropic / Claude Sonnet','OpenAI / GPT-4o','prompt-registry/v2','Sending tenancy notices',1,98.5,'Approved-template communications only.',true),
('wd-planner','Wedding Planner Agent','Builds planning timelines and coordinates wedding logistics.','site_specific','planning',(SELECT id FROM ai_sites WHERE site_key='wedora'),'production','active','healthy','low','limited_automatic','Vowora Ops','Vowora Escalations','Anthropic / Claude Sonnet','OpenAI / GPT-4o','prompt-registry/v2','Building planning timeline',1,98.3,'Wedding planning coordination.',true),
('wd-guest','Guest Agent','Assists wedding guests with RSVP and event information.','site_specific','support',(SELECT id FROM ai_sites WHERE site_key='wedora'),'production','active','healthy','low','limited_automatic','Vowora Support','Vowora Escalations','Anthropic / Claude Sonnet','OpenAI / GPT-4o','prompt-registry/v2','Answering guest query',2,99.0,'Guest-facing support.',true),
('wd-rsvp','RSVP Agent','Processes RSVP responses and tracks guest attendance.','site_specific','operations',(SELECT id FROM ai_sites WHERE site_key='wedora'),'production','active','healthy','low','limited_automatic','Vowora Ops','Vowora Escalations','Anthropic / Claude Sonnet','OpenAI / GPT-4o','prompt-registry/v2','Processing RSVP batch',0,99.4,'RSVP processing and tracking.',true),
('wd-invitation','Invitation Agent','Designs and sends wedding invitations and manages invite lists.','site_specific','communications',(SELECT id FROM ai_sites WHERE site_key='wedora'),'production','active','healthy','low','limited_automatic','Vowora Ops','Vowora Escalations','Anthropic / Claude Sonnet','OpenAI / GPT-4o','prompt-registry/v2','Preparing invitation batch',0,98.7,'Invitation design and delivery.',true),
('wd-supplier','Supplier Agent','Coordinates with wedding suppliers and chases quotes.','site_specific','operations',(SELECT id FROM ai_sites WHERE site_key='wedora'),'production','active','healthy','medium','limited_automatic','Vowora Ops','Vowora Escalations','Anthropic / Claude Sonnet','OpenAI / GPT-4o','prompt-registry/v2','Chasing supplier quote',1,96.6,'Supplier coordination.',true),
('wd-budget','Budget Agent','Tracks wedding budgets and flags overspend.','site_specific','billing',(SELECT id FROM ai_sites WHERE site_key='wedora'),'production','active','healthy','medium','recommend_only','Vowora Ops','Vowora Escalations','Anthropic / Claude Sonnet','OpenAI / GPT-4o','prompt-registry/v2','Tracking budget categories',0,98.1,'Budget tracking — recommend-only.',true),
('wd-seating','Seating Agent','Builds and validates seating charts and table arrangements.','site_specific','planning',(SELECT id FROM ai_sites WHERE site_key='wedora'),'production','idle','healthy','medium','limited_automatic','Vowora Ops','Vowora Escalations','Anthropic / Claude Sonnet','OpenAI / GPT-4o','prompt-registry/v2','Validating seating chart',0,97.1,'Seating plan generation and validation.',true),
('wd-timeline','Timeline Agent','Builds day-of wedding timelines and run sheets.','site_specific','planning',(SELECT id FROM ai_sites WHERE site_key='wedora'),'production','active','healthy','low','limited_automatic','Vowora Ops','Vowora Escalations','Anthropic / Claude Sonnet','OpenAI / GPT-4o','prompt-registry/v2','Building day-of timeline',0,98.9,'Day-of timeline generation.',true),
('wd-comms','Wedding Communications Agent','Sends approved wedding communications to couples and guests.','site_specific','communications',(SELECT id FROM ai_sites WHERE site_key='wedora'),'production','active','healthy','low','limited_automatic','Vowora Ops','Vowora Escalations','Anthropic / Claude Sonnet','OpenAI / GPT-4o','prompt-registry/v2','Sending guest update',1,98.6,'Approved-template wedding communications.',true),
('wd-photo','Photo Moderation Agent','Reviews and moderates wedding photos and shared media.','site_specific','data',(SELECT id FROM ai_sites WHERE site_key='wedora'),'production','active','healthy','medium','limited_automatic','Vowora Ops','Vowora Escalations','Anthropic / Claude Sonnet','OpenAI / GPT-4o','prompt-registry/v2','Moderating photo upload',0,97.9,'Photo and media moderation.',true),
('tf-master','Forge Master Agent','Coordinates the internal build pipeline and orchestrates Forge agents.','site_specific','orchestration',(SELECT id FROM ai_sites WHERE site_key='the-forge'),'production','active','warning','high','autonomous','Forge Team','Group Incident Team','OpenAI / GPT-4o','Anthropic / Claude Sonnet','prompt-registry/code-v3','Coordinating build pipeline',2,95.4,'Orchestrates Forge build agents.',true),
('tf-prompt','Prompt Builder Agent','Refines and version-controls prompt templates for code generation.','site_specific','development',(SELECT id FROM ai_sites WHERE site_key='the-forge'),'production','idle','healthy','medium','recommend_only','Forge Team','Group Incident Team','OpenAI / GPT-4o','Anthropic / Claude Sonnet','prompt-registry/code-v3','Refining prompt templates',0,97.0,'Prompt engineering and versioning.',true),
('tf-page','Page Designer Agent','Generates page layouts and UI designs for build requests.','site_specific','development',(SELECT id FROM ai_sites WHERE site_key='the-forge'),'production','active','healthy','medium','limited_automatic','Forge Team','Group Incident Team','OpenAI / GPT-4o','Anthropic / Claude Sonnet','prompt-registry/code-v3','Designing page layout',1,96.5,'Page and UI generation.',true),
('tf-component','Component Agent','Generates and maintains reusable UI components.','site_specific','development',(SELECT id FROM ai_sites WHERE site_key='the-forge'),'production','active','healthy','medium','limited_automatic','Forge Team','Group Incident Team','OpenAI / GPT-4o','Anthropic / Claude Sonnet','prompt-registry/code-v3','Generating component',0,96.8,'Component generation and reuse.',true),
('tf-code','Code Agent','Generates and reviews code for build requests.','site_specific','development',(SELECT id FROM ai_sites WHERE site_key='the-forge'),'production','error','warning','high','limited_automatic','Forge Team','Group Incident Team','OpenAI / GPT-4o','Anthropic / Claude Sonnet','prompt-registry/code-v3','Fixing failing generation',1,93.8,'Code generation; recent failures under investigation.',true),
('tf-database','Database Agent','Generates database schemas, migrations and queries.','site_specific','development',(SELECT id FROM ai_sites WHERE site_key='the-forge'),'production','active','healthy','high','human_approval_required','Forge Team','Group Incident Team','OpenAI / GPT-4o','Anthropic / Claude Sonnet','prompt-registry/code-v3','Drafting migration',0,96.0,'Schema changes require human approval.',true),
('tf-auth','Authentication Agent','Generates and reviews authentication and identity flows.','site_specific','security',(SELECT id FROM ai_sites WHERE site_key='the-forge'),'production','active','healthy','critical','human_approval_required','Forge Team','Group Incident Team','OpenAI / GPT-4o','Anthropic / Claude Sonnet','prompt-registry/code-v3','Reviewing auth flow',0,96.3,'Auth changes require security review.',true),
('tf-integration','Integration Agent','Generates and wires third-party integrations.','site_specific','development',(SELECT id FROM ai_sites WHERE site_key='the-forge'),'production','active','healthy','medium','limited_automatic','Forge Team','Group Incident Team','OpenAI / GPT-4o','Anthropic / Claude Sonnet','prompt-registry/code-v3','Wiring integration',0,96.6,'Third-party integration generation.',true),
('tf-asset','Asset Agent','Generates and optimises digital assets and media.','site_specific','development',(SELECT id FROM ai_sites WHERE site_key='the-forge'),'production','active','healthy','low','limited_automatic','Forge Team','Group Incident Team','OpenAI / GPT-4o','Anthropic / Claude Sonnet','prompt-registry/code-v3','Optimising asset',0,97.5,'Asset generation and optimisation.',true),
('tf-seo','SEO Agent','Generates and validates SEO metadata and structure.','site_specific','reporting',(SELECT id FROM ai_sites WHERE site_key='the-forge'),'production','active','healthy','low','limited_automatic','Forge Team','Group Incident Team','Anthropic / Claude Sonnet','OpenAI / GPT-4o','prompt-registry/v2','Validating SEO tags',0,98.0,'SEO metadata generation.',true),
('tf-accessibility','Accessibility Agent','Checks and fixes accessibility issues in generated code.','site_specific','testing',(SELECT id FROM ai_sites WHERE site_key='the-forge'),'production','active','healthy','medium','limited_automatic','Forge Team','Group Incident Team','Anthropic / Claude Sonnet','OpenAI / GPT-4o','prompt-registry/v2','Auditing accessibility',0,97.8,'Accessibility auditing and fixes.',true),
('tf-security','Security Agent','Scans generated code for security vulnerabilities.','site_specific','security',(SELECT id FROM ai_sites WHERE site_key='the-forge'),'production','active','healthy','high','human_approval_required','Forge Team','Group Incident Team','OpenAI / GPT-4o','Anthropic / Claude Sonnet','prompt-registry/code-v3','Scanning code for issues',0,97.9,'Security scanning; findings human-reviewed.',true),
('tf-test','Testing Agent','Runs release validation tests and unit test suites.','site_specific','testing',(SELECT id FROM ai_sites WHERE site_key='the-forge'),'production','active','warning','medium','limited_automatic','Forge Team','Group Incident Team','OpenAI / GPT-4o','Anthropic / Claude Sonnet','prompt-registry/code-v3','Running release validation',1,96.1,'Release validation — latest build flagged.',true),
('tf-repair','Repair Agent','Repairs failing builds and generation issues.','site_specific','repair',(SELECT id FROM ai_sites WHERE site_key='the-forge'),'production','idle','healthy','medium','human_approval_required','Forge Team','Group Incident Team','OpenAI / GPT-4o','Anthropic / Claude Sonnet','prompt-registry/code-v3','Awaiting build failures',0,95.9,'Build repairs require approval.',true),
('tf-publishing','Publishing Agent','Coordinates publishing and deployment of generated sites.','site_specific','infrastructure',(SELECT id FROM ai_sites WHERE site_key='the-forge'),'production','active','healthy','high','human_approval_required','Forge Team','Group Incident Team','Anthropic / Claude Sonnet','OpenAI / GPT-4o','prompt-registry/v2','Preparing publish',0,96.4,'Publishing gated behind release approval.',true),
('tf-docs','Documentation Agent','Generates and maintains documentation for generated projects.','site_specific','reporting',(SELECT id FROM ai_sites WHERE site_key='the-forge'),'production','active','healthy','low','limited_automatic','Forge Team','Group Incident Team','Anthropic / Claude Sonnet','OpenAI / GPT-4o','prompt-registry/v2','Generating documentation',0,98.3,'Documentation generation.',true)
ON CONFLICT (agent_key) DO UPDATE SET name=EXCLUDED.name, description=EXCLUDED.description, agent_type=EXCLUDED.agent_type, category=EXCLUDED.category, site_id=EXCLUDED.site_id, environment=EXCLUDED.environment, status=EXCLUDED.status, health=EXCLUDED.health, risk_level=EXCLUDED.risk_level, autonomy_level=EXCLUDED.autonomy_level, owner_team=EXCLUDED.owner_team, escalation_team=EXCLUDED.escalation_team, primary_model_reference=EXCLUDED.primary_model_reference, fallback_model_reference=EXCLUDED.fallback_model_reference, prompt_version_reference=EXCLUDED.prompt_version_reference, current_task=EXCLUDED.current_task, queue_count=EXCLUDED.queue_count, success_rate=EXCLUDED.success_rate, notes=EXCLUDED.notes, is_active=EXCLUDED.is_active;